version: "3.7"
# docker-compose up -d --build
# docker-compose up -d
volumes:
  wpDbData:

networks:
  wpNetwork:

services:
  # DB Service

  db:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    container_name: stnc-wpu-maria
    volumes:
      - wpDbData:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: a12345

      MYSQL_DATABASE: wordpress

      MYSQL_USER: wpuser

      MYSQL_PASSWORD: wppassword

    ports:
      - 9089:3306

    restart: always

    networks:
      - wpNetwork
    volumes: ["./:/var/www/mysqlData"]
  # phpmyadmin
    #  command: >
    # bash -c "python manage.py migrate
    # && python manage.py runserver 0.0.0.0:8000"

  phpmyadmin:
    depends_on:
      - db
    container_name: stnc-wpu-phpmyadmin
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:5.0.2

    environment:
      PMA_HOST: db

      MYSQL_USER: wpuser

      MYSQL_PASSWORD: wppassword

      MYSQL_ROOT_PASSWORD: a12345

  

    ports:
      - 9082:80

    restart: always

    networks:
      - wpNetwork

  # wordpress

  wordpress:
    container_name: stnc-wpu-wordpress
    depends_on:
      - db

    image: wordpress:latest

    ports:
      - 9083:80

      # - 443:443

    restart: always

    environment:
      WORDPRESS_DB_HOST: db

      WORDPRESS_DB_USER: wpuser

      WORDPRESS_DB_PASSWORD: wppassword
      # WORDPRESS_DEBUG: 1
      # WORDPRESS_CONFIG_EXTRA: |
      #   define( ""WP_DEBUG_LOG"", true );
      #   define( ""WP_DEBUG_DISPLAY"", true );
     
    volumes: 
      - "./:/var/www/html"
                  # Theme, plugins and uploads
      # - ./wp-content:/var/www/html/wp-content
      # Configurations
      # - .htaccess:/var/www/html/.htaccess
      # PHP Configuration
      - ./php-extra.ini:/usr/local/etc/php/conf.d/php-extra.ini
    networks:
      - wpNetwork
