version: "3.7"
# docker-compose up -d --build
# docker-compose up -d
volumes:
  wpDbData:

networks:
  wpNetwork:

services:
  # DB Service

  db:
    image: mariadb:10.5.8
    container_name: stnc-wp-maria
    volumes:
      - wpDbData:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: a12345

      MYSQL_DATABASE: wordpress

      MYSQL_USER: wpuser

      MYSQL_PASSWORD: wppassword

    ports:
      - 8889:3306

    restart: always

    networks:
      - wpNetwork
    volumes: ["./:/var/www/mysqlData"]
  # phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    container_name: stnc-wp-phpmyadmin
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:5.0.2

    environment:
      PMA_HOST: db

      MYSQL_USER: wpuser

      MYSQL_PASSWORD: wppassword

      MYSQL_ROOT_PASSWORD: a12345

  

    ports:
      - 8082:80

    restart: always

    networks:
      - wpNetwork

  # wordpress

  wordpress:
    container_name: stnc-wp-wordpress
    depends_on:
      - db

    image: wordpress:latest

    ports:
      - 8083:80

      # - 443:443

    restart: always

    environment:
      WORDPRESS_DB_HOST: db

      WORDPRESS_DB_USER: wpuser

      WORDPRESS_DB_PASSWORD: wppassword
      # WORDPRESS_DEBUG: 1
      # WORDPRESS_CONFIG_EXTRA: |
      #   define( 'WP_DEBUG_LOG', true );
      #   define( 'WP_DEBUG_DISPLAY', true );
     
    volumes: ["./:/var/www/html"]

    networks:
      - wpNetwork
