version: "3.8"
#docker-compose up -d --build
# https://nemoz.info/run-mysql-from-docker-and-allow-access-from-outside-container/
#https://linuxhandbook.com/get-container-ip/ 
services:
  mysql_db_container:
    container_name: 'stnc-mysql'
    # image: mariadb:10.6
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: selman123
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    networks:
      - mysqlTool
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phpmyadmin:
    container_name: 'stnc-phpmyadmin'
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql_db_container
    depends_on:
      - mysql_db_container
    ports:
      - "9191:80"
    networks:
      - mysqlTool

  adminer:
    container_name: 'stnc-adminer'
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
     - mysql_db_container
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    networks:
    - mysqlTool

networks:
  mysqlTool:
    driver: bridge

volumes:
  mysql_db_data_container:     
